dist: bionic
language: crystal
crystal:
  - latest
  - nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install -y llvm-7-dev libclang-7-dev

script:
  - shards update
  - make
  - ./tests/backend/test-runner
  - ./tests/frontend/test-all
